acrpapp/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
# from django.contrib.auth import views
urlpatterns = [
    path('', views.index, name='index'),
    path('application/', views.application, name='application'),
    path('<int:pk>/', views.DesignAppDetailView.as_view(), name='designapp_detail'),
    path('login/',views.evaluator_login,name='evaluator_login'),
    path('acrp/', views.acrp, name='acrp'),
    path('process/', views.process, name='process'),
    path('process_detail/<str:ekey>/', views.process_detail, name='process_detail'),
    path('processed/', views.processed, name='processed'),
    path('processed_detail/<str:ekey>/', views.processed_detail, name='processed_detail'),
    path('Applicant/', views.Applicanturl, name='Applicanturl'),
    path('Applicant21/', views.Applicanturl21, name='Applicanturl21'),
    path('Applicantdetail/<str:ekey>/', views.Applicantdetail, name='Applicantdetail'),
    path('Applicantdetail21/<str:ekey>/', views.Applicantdetail21, name='Applicantdetail21'),
    path('elogin/',views.user_login,name='user_login'),
    path('reviewerLogin/',views.reviewer_login,name='reviewer_login'),
    path('acrpmembers/', views.acrpmembers, name='acrpmembers'),
    path('evaluator/', views.evaluator, name='evaluator'),
    path('sorted/', views.sorted_id, name='sorted_id'),
    path('sorted_area/', views.sorted_area, name='sorted_area'),
    path('avgscore_designarea/', views.avgscore_designarea, name='avgscore_designarea'),
    path('avgscore/', views.avgscore, name='avgscore'),
    path('evaluator_detail/<str:ekey>/', views.evaluator_detail, name='evaluator_detail'),
    path('saved/<str:ekey>/', views.saved, name='saved'),
    path('completedsubmissions/', views.completedsubmissions, name='completedsubmissions'),
    path('completedsubmissions_detail/<str:ekey>/', views.completedsubmissions_detail, name='completedsubmissions_detail'),
    path('completedsubmissions_detail/<str:ekey>/<int:evalutor_id>/', views.sort_detail, name='sort_detail'),
    path('reedit/',views.reedit,name='reedit')
    
]

acrpsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('acrpapp.urls')),
    path('acrpapp/', include('acrpapp.urls')),
    path('graward/', include('polls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('media/',include('')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required, permission_required
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('index', views.index, name='index'),
    path('evaluator/search', views.search, name='search'),
    path('evaluator/saved_application/<int:Applicant_details_id>/', views.saved_application, name='saved_application'),
    path('evaluator/submit', views.submit, name='submit'),
    path('evaluator/submit_application/<int:Applicant_details_id>/', views.submit_application, name='submit_application'),
    path('advisor/<str:cheque_no>/<int:ref_num>', views.advisor, name='advisor'),
    path('FacultyAdvisorRecommendation/<str:cheque_no>/<int:ref_num>', views.FacultyAdvisorRecommendation, name='FacultyAdvisorRecommendation'),
    path('', TemplateView.as_view(template_name='polls/urls.html')),
    path('errorreq', TemplateView.as_view(template_name='polls/extra.html')),
    path('elog/',views.user,name='user'),
    path('grareviewers/',views.reviewer_login , name = 'grareviewer'),
    path('errorvisa/', TemplateView.as_view(template_name='polls/errorvisa.html')),
    path('CoverPage2021_KW',TemplateView.as_view(template_name='pdf/CoverPage2021_KW.html')),
    path('GraduateResearchAwardProgramApplication',TemplateView.as_view(template_name='pdf/Application For Graduate Research Award Program_Instructions.html')),
    # path('', TemplateView.as_view(template_name='polls/mainpage.html')),
    path('support/process', views.process, name='process'),
    path('support/process_detail/<int:Applicant_details_id>/', views.process_detail, name='process_detail'),
    path('support/processed', views.processed, name='processed'),
    path('support/processed_detail/<int:Applicant_details_id>/', views.processed_detail, name='processed_detail'),
    path('recom/<str:cheque_no>/<int:ref_num>', views.getrecommendations, name='getrecommendations'),
    path('advisorrecommendation/<str:cheque_no>/<int:ref_num>', views.facultygetrecommendation, name='facultygetrecommendation'),
    path('support/', views.support,name='support'),
    path('openview', views.RecommendationsAllInternal, name=' RecommendationsAllInternal'),
    path('evaluators', views.evaluators,name='evaluators'),
    path('EvaluateSubmissions', views.EvaluateSubmissions, name='EvaluateSubmissions'),
    path('EvaluateSubmissions_detail/<int:Applicant_details_id>/', views.EvaluateSubmissions_detail, name='EvaluateSubmissions_detail'),
    path('EvaluateSubmissionsSaved_detail/<int:Applicant_details_id>/', views.EvaluateSubmissionsSaved_detail, name='EvaluateSubmissionsSaved_detail'),
    path('CompletedSubmissions', views.CompletedSubmissions, name='CompletedSubmissions'),
    path('compute_average_detail/<int:a_id>/', views.compute_average_detail, name='compute_average_detail'),
    path('log/',views.user_prof,name='user_prof'),
    path('support/compute_average', views.compute_average, name='compute_average'),
    path('support/compute_average_detail/<int:a_id>/', views.compute_average_detail, name='compute_average_detail'),
    path('support/enable',views.enableCompleteSubmissions,name='enableCompleteSubmissions'),
    path('support/averagescore',views.Average_score,name='Average_score'),
    path('support/lastname',views.Last_Name,name='Last_Name'),
    path('support/reedit',views.reedit,name='reedit'),
    path('support/adminupdatescore',views.adminupdatescore,name='updatescore'),
    path('support/evaluatorupdatescore',views.evaluatorupdatescore,name='evaluatorupdatescore'),
    path('support/reference_reminder',views.reference_reminder,name='reference_reminder'),
    path('support/EvaluateSubmissionsSaved_detail/<int:Applicant_details_id>/', views.EvaluateSubmissionsSaved_detail, name='EvaluateSubmissionsSaved_detail'),
    # path('acrp/support/userlogin/',views.user_login,name='user_login'),
    path('support/EvaluateSaved_detail/<int:Applicant_details_id>/<int:eval_id>/',views.EvaluateSaved_detail,name='EvaluateSaved_detail'),
    # path('acrp/support/EvaluateSaved_detail/<int:Applicant_id>/', views.EvaluateSaved_detail, name='EvaluateSaved_detail'),
    # path('acrp/login/', views.login, name ='login'), 



]

acrpapp/models.py
from django.contrib.auth.models import AbstractUser 
from django.utils.translation import gettext_lazy
from django.conf import settings
from django.contrib.auth.models import User
from encrypted_id.models import EncryptedIDModel
from .validators import validate_file_size
from django.db import models

# Create your models here.
class Applicant(EncryptedIDModel):
    Advisor1_FirstName=models.CharField(max_length=128,null=True)
    Advisor1_LastName=models.CharField(max_length=30,default=None,null=True)
    Advisor1_Department=models.CharField(max_length=100,default=None,null=True)
    Advisor1_Inst = models.CharField(max_length=128,default='')
    Advisor1_Street_Address=models.CharField(max_length=128,default=None,null=True)
    Advisor1_City=models.CharField(max_length=50,default=None,null=True)
    US_STATES = [('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')
    ]
    Advisor1_State=models.CharField(max_length=50,choices=US_STATES,default="",null=True)
    Advisor1_Zip_Code=models.IntegerField(max_length=13,default=None,null=True)
    Advisor1_Telephone=models.BigIntegerField(max_length=13,default=None,null=True)
    Advisor1_Fax=models.CharField(max_length=30,default=None,null=True)
    Advisor1_Email=models.EmailField(max_length=128,default=None,null=True)
    Advisor2_FirstName=models.CharField(max_length=128,default='',blank=True)
    Advisor2_LastName=models.CharField(max_length=30,default='',blank=True)
    Advisor2_Department=models.CharField(max_length=100,default='',blank=True)
    Advisor2_Inst = models.CharField(max_length=128,default='',blank=True)
    Advisor2_Street_Address=models.CharField(max_length=128,default='',blank=True)
    Advisor2_City=models.CharField(max_length=50,default='',blank=True)
    US___STATES = [('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')
    ]
    Advisor2_State=models.CharField(max_length=50,choices=US___STATES,default='',blank=True) 
    Advisor2_Zip_Code=models.CharField(max_length=20,default='',blank=True)
    Advisor2_Telephone=models.CharField(max_length=13,default='',blank=True)
    Advisor2_Fax=models.CharField(max_length=30,default='',blank=True)
    Advisor2_Email=models.EmailField(max_length=128,default='',blank=True)
    FAAAE = 'AE'
    FAAAM = 'AM'
    FAAAO = 'AO'
    FAARS = 'RS'
    DesignAreaChoices = [
        (FAAAE, 'Airport Environmental Interactions'),
        (FAAAM, 'Airport Management and Planning'),
        (FAAAO, 'Airport Operations and Maintenance'),
        (FAARS, 'Runway Safety/Runway Incursions/Runway Excursions Including Aprons,Ramps,and Taxiways'),
    ]
    design_area = models.CharField(max_length=50,choices=DesignAreaChoices,default="")
    Specific_Challenge=models.CharField(max_length=264,default="")
    Briefly_Describe=models.CharField(max_length=264,default="")
    team=[
             ('Student Team','Student Team'),
             ('Individual Student','Individual Student'),
         ]
    project_team=models.CharField(max_length=50,choices=team,default="")
    undertaken=[
               ('Design Class','Design Class'),
               ('Independent Study','Independent Study'),
               ('Student Society Chapter','Student Society Chapter'),
               ('Other','Other'),
               ]
    project_undertaken=models.CharField(max_length=50,choices=undertaken,default="")
    Other = models.CharField(max_length=100,blank=True)
    RADIOS = [
    ('Undergraduate','Undergraduate'),
    ('Graduate','Graduate'),
    ('Both','Both'),
    ]
    Students_Involved=models.CharField(
         max_length=50,
         choices=RADIOS,
         default="",
    )
    UG_level=models.CharField(max_length=50,blank=True)
    no_of_participants_UG=models.PositiveIntegerField(default="0")
    no_of_participants_G=models.PositiveIntegerField(default="0")
    no_of_participants_FA=models.PositiveIntegerField(default="0")
    no_of_participants_Other = models.CharField(max_length=200,blank=True)


    semester=models.CharField(max_length=50,default="",)
    created_at = models.DateField(auto_now_add=True, blank=True)






class DesignApp(EncryptedIDModel):
    Inst = models.CharField(max_length=128,default="",)
    title = models.CharField(max_length=200,default="")

    FAAAE = 'AE'
    FAAAM = 'AM'
    FAAAO = 'AO'
    FAARS = 'RS'
    DesignAreaChoices = [
        (FAAAE, 'Airport Environmental Interactions'),
        (FAAAM, 'Airport Management and Planning'),
        (FAAAO, 'Airport Operations and Maintenance'),
        (FAARS, 'Runway Safety/Runway Incursions/Runway Excursions'),
    ]
    design_area = models.CharField(max_length=3,choices=DesignAreaChoices,)
    Specific_Challenge=models.CharField(max_length=264,default="")

    RADIOS = [
    ('Undergraduate','Undergraduate'),
    ('Graduate','Graduate'),
    ('Both','Both'),
    ]
    Students_Involved=models.CharField(
         max_length=20,
         choices=RADIOS,
         default="",
    )
    Advisor1_FirstName=models.CharField(max_length=128,null=True)
    Advisor1_LastName=models.CharField(max_length=30,default=None,null=True)
    Advisor1_Department=models.CharField(max_length=100,default=None,null=True)
    Advisor1_Street_Address=models.CharField(max_length=128,default=None,null=True)
    Advisor1_City=models.CharField(max_length=50,default=None,null=True)
    US_STATES = [('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')
    ]
    Advisor1_State=models.CharField(max_length=50,choices=US_STATES,default="",null=True)
    Advisor1_Zip_Code=models.IntegerField(max_length=13,default=None,null=True)
    Advisor1_Telephone=models.BigIntegerField(max_length=13,default=None,null=True)
    Advisor1_Fax=models.CharField(max_length=30,default=None,null=True)
    Advisor1_Email=models.EmailField(max_length=128,default=None,null=True)
    Advisor2_FirstName=models.CharField(max_length=128,default='',blank=True)
    Advisor2_LastName=models.CharField(max_length=30,default='',blank=True)
    Advisor2_Department=models.CharField(max_length=100,default='',blank=True)
    Advisor2_Street_Address=models.CharField(max_length=128,default='',blank=True)
    Advisor2_City=models.CharField(max_length=50,default='',blank=True)

acrpapp/templates/acrpapp/Thankyou.html
<!DOCTYPE html>
<html>
<head>
	<title>Application SUbmitted</title>
</head>
<body>
	<div class="container">

		{{ f.created_at }}

		<h2>Thank you, {{ f.Advisor1_FirstName }} {{ f.Advisor1_LastName }}, for submitting the design package for the ACRP University Design Competition for Addressing Airport Needs.</h2>
	</div>

</body>
</html>

acrpapp/templates/acrpapp/acrp_support.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <style>
  	#text-container
{
width: 400px;
Display: block;
Float: left;
}
  </style>
</head>
<body>
<div class="container">
  <div class="jumbotron">
  <h4>Airport Cooperative Research Program (ACRP) University Design Competition for Addressing Airport Needs VSGC Support Members Page</h4>
</div>
<div style="text-align: center;">
<div style="display: inline-block; text-align: left;">
<ul>
<li><a href="/Applicant/">View Notice of Intent Submissions</a><br></li>
<li><a href="/process/">Process Competition Submissions</a><br></li>
<li><a href="/processed/">View processed Submissions</a><br></li>
<li><a href="/sorted/">View Evaluations Sorted by ID</a><br></li>
<li><a href="/avgscore/">View Evaluations Sorted by Average Score</a><br></li>
<li><a href="/avgscore_designarea/">View Evaluations Avg. Score Sorted by Design Challenge</a><br></li>
<li><a href="/sorted_area/">View Evaluations Sorted by Design Challenge</a><br></li>
<li><a href="/reedit/">Enable Re-Editing</a>
</ul>
</div>
</div>
</div>
</body>
</html>

acrpapp/templates/acrpapp/acrpmembers.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
<div class="container">
  <div class="jumbotron">
  <h4>Airport Cooperative Research Program (ACRP) University Design Competition for Addressing Airport Needs VSGC Support Members Page</h4>
</div>
<div style="text-align: center;">
<div style="display: inline-block; text-align: left;">
<ul>
<li><a href="/evaluator/">Evaluate Submissions</a><br></li>
<li><a href="/completedsubmissions/">View Completed Submissions</a></li>
</ul>
</div>
</div>
</div>
</body>
</html>

acrpapp/templates/acrpapp/avgscore.html
{% load acrp_extras %}
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title></title>
<style>
table, th, td {
  border-collapse: collapse;
}
th, td {
  padding: 15px;
}
</style>
</head>
<body>
  <div class="jumbotron">
  <h4>Airport Cooperative Research Program (ACRP) University Design Competition for Addressing Airport Needs</h4>
</div>
  <div class="container">
<div class="text-md-center">
<h5>Design Evaluations by average score</h5>
</div>
<br>
{% for dAppType, dAppValue in dResult.items %}
<table style="width:100%">
   <tr>
    <th>Reviewer</th>
    <th>Q1</th>
    <th>Q2</th>
    <th>Q3</th>
    <th>Q4</th>
    <th>Q5</th>
    <th>Q6</th>
    <th>Q7</th>
    <th>Q8</th>
    <th>Q9</th>
    <th>Total</th> 
  </tr>
    <h5><i>{{ dAppType }}--- Average : {{ dAvg|get_item:dAppType }}</i> </h5>

  {% for designApp in dAppValue %}
  <tr>
{% byte2str keys|get_item:designApp.design_app_id as eKey %}
    <td><a href="/completedsubmissions_detail/{{eKey}}/{{ designApp.evalutor_id_id }}/">{{ evals|get_item:designApp.evalutor_id_id }}</a></td>
    {% for j in dApps|get_item:designApp.id %}
      <td>{{ j.Q_score }}</td>
    {% endfor %}
  </tr>
  {% endfor %}
  {% endfor %}

</table>
<br>
</div>
</body>
</html>

acrpapp/templates/acrpapp/designapp_detail.html
<h1>{{ object.title }}</h1>

acrpapp/templates/acrpapp/designapp_list.html
<h1>Articles</h1>
<ul>
{% for article in object_list %}
    <li><a href="{{article.id}}">{{ article.title }}</a> - {{ article.get_design_area_display }} </li>
{% empty %}
    <li>No submission yet.</li>
{% endfor %}
</ul>

acrpapp/templates/acrpapp/duplicate.html
{% load polls_extras %}
<!DOCTYPE html>
<html>
<head>
   <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <title></title>
<style>
table, th, td {
  border-collapse: collapse
}
th, td {
  padding: 15px;
}
</style>
</head>
<body>

  <div class="jumbotron">
  <h4 style="text-align: center">Graduate Research Program on Public-Sector Aviation Issues</h4>

</div>

{{ daDB }}
<!--   <div class="container">
<div class="text-md-center">
<h5>Processed Submissions</h5>
</div>
<br>


{% for xvalue in dApps %}
<table style="width:100%">
  <tr>
  <th>First Name</th>
  <th>Degree objective</th>
  <th>Major Field</th>
  <th>College/University Enrolled</th>
  <th>Status</th>
</tr>
{% for object in xvalue %}
<tr>
{% if object.stat == 'Pending' %}

<td><a href="/acrpsite/acrp/EvaluateSubmissions_detail/{{object.Applicant_id}}/">{{ evaluate.App_FirstName }}</a></td>
    <td>{{ evaluate.Degree_objective }}</td>
    <td>{{ evaluate.Major_Field }}</td>
    <td>{{ evaluate.clg_or_univ_Enrolled }}</td>
    <td>{{ object.stat }}</td>
   {% elif object.stat == 'Evaluation Saved' %}
   <td><a href="/acrpsite/acrp/EvaluateSubmissionsSaved_detail/{{object.Applicant_id}}/">{{ evaluate.App_FirstName }}</a></td>
    <td>{{ evaluate.Degree_objective }}</td>
    <td>{{ evaluate.Major_Field }}</td>
    <td>{{ evaluate.clg_or_univ_Enrolled }}</td>
    <td>{{ object.stat }}</td>
  {% endif %}
  {% endfor %}
  </tr>
</table>
 {% endfor %}
 </div>
 --></body>
</html>
 --><!-- {% for dAppType, dAppValue in dApps.items %}
<table style="width:100%">
    <tr>
  <th>First Name</th>
  <th>Degree objective</th>
  <th>Major Field</th>
  <th>College/University Enrolled</th>
  <th>Status</th>

</tr>
<tr>
  {% for Applicant, userProfile in dAppValue %}
  <p>{{ userProfile.stat }}</p>
  {% if userProfile.stat == 'Pending' %}
    <td><a href="/acrpsite/acrp/EvaluateSubmissions_detail/{{value.id}}/">{{ Applicant.App_FirstName }}</a></td>
    <td>{{ Applicant.Degree_objective }}</td>
    <td>{{ Applicant.Major_Field }}</td>
    <td>{{ Applicant.clg_or_univ_Enrolled }}</td>
    <td>{{ userProfile.stat }}</td>
  {% else %}
  <td><a href="/acrpsite/acrp/EvaluateSubmissions_detail/{{value.id}}/">{{ Applicant.App_FirstName }}</a></td>
    <td>{{ Applicant.Degree_objective }}</td>
    <td>{{ Applicant.Major_Field }}</td>
    <td>{{ Applicant.clg_or_univ_Enrolled }}</td>
    <td>{{ userProfile.stat }}</td>
  {% endif %}
</tr>
{% endfor %}
</table>
<br>
{% endfor %}
 --><!-- </div>
</body>
</html>

acrpapp/templates/acrpapp/errormsg.html
<!DOCTYPE html>
<html>
<head>
	<title>ERROR MESSAGE</title>
</head>
<body>
	
	<h3>Your form is not submitted</h3>
	{{ form.errors }}
{{ form.non_field_errors }}

</body>
</html>